CREATE TABLE ADDRESS (
	ADD_ID INT PRIMARY KEY ,
    DEL_ADD_1 VARCHAR(50) ,
    DEL_ADD_2 VARCHAR(50) ,
    CITY VARCHAR(50),
    ZIPCODE VARCHAR(50) 
    ) ;
DROP TABLE ADDRESS ;
SELECT * FROM ADDRESS ;    
INSERT INTO ADDRESS VALUES (25,'RAJIV CHOWK - SAI SINGH BLDG','HAR HAR GANGE MANDIR','RATNAGIRI',53495);
INSERT INTO ADDRESS VALUES (26,'RAJIV CHOWK - GOKULDHAM ','JAI MAHAKAL','RATNAGIRI',53499);
INSERT INTO ADDRESS VALUES (27,'RAJIV CHOWK - MAHESHWAR BLDG','VAISHNAV MATA','RATNAGIRI',53497);
INSERT INTO ADDRESS VALUES (28,'RAJIV CHOWK - Rameshwar BLDG','Durga MATA','Sangli',53542);
INSERT INTO ADDRESS VALUES (29,'RAJIV CHOWK - Tiruvanant BLDG','Jaggannath','Sangli',53587);

