CREATE TABLE ROTATIONAL_SHIFT (
						ROW_ID INT PRIMARY KEY ,
                        ROTA_ID INT NOT NULL,
                        DATE_ DATE NOT NULL ,
                        SHIFT_ID INT NOT NULL  , 
                        STAFF_ID INT NOT NULL ,
                        FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT(SHIFT_ID) ,
                        FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
                        );
DROP TABLE ROTATIONAL_SHIFT ;
SELECT * FROM ROTATIONAL_SHIFT ;
INSERT INTO ROTATIONAL_SHIFT VALUES (1 , 91,DATE('2023-12-06'),101,1);
INSERT INTO ROTATIONAL_SHIFT VALUES (2 , 92,DATE('2023-12-06'),102,1);
INSERT INTO ROTATIONAL_SHIFT VALUES (3 , 99,DATE('2023-12-06'),103,1);