CREATE TABLE STAFF (
			STAFF_ID INT PRIMARY KEY ,
            FIRST_NAME VARCHAR(50) NOT NULL ,
            LAST_NAME VARCHAR(50) NOT NULL ,
            POSITION VARCHAR(50) NOT NULL ,
            HOURLY_RATE INT NOT NULL 
            ) ;
DROP TABLE STAFF ;
SELECT * FROM STAFF ;
INSERT INTO STAFF VALUES (1,'DEEPAK' ,'KULAL' ,'CHEF' ,15);
INSERT INTO STAFF VALUES (2,'RAKHI' ,'SOBAN' ,'CLEANER' ,12);
INSERT INTO STAFF VALUES (3,'YO' ,'GOJINDER' ,'CASHIER' ,20);
